version: "3.8"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "57000:8080"
    command:
      - "./bin/linux/run_uvicorn_server.sh"
    volumes:
      - .:/workspace

  ui: 
    build:
      context: ./freemocap-ui
      dockerfile: Dockerfile.ui
    ports:
      - "57001:3000"
    command:
      - "npm"
      - "start"
    volumes:
      - .:/workspace

  # db:
  #   image: postgres:14-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
