[project]
name = "freemocap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aniposelib>=0.7.0",
    "freemocap-blender-addon",
    "libsass>=0.23.0",
    "opencv-contrib-python>=4.8.1.78",
    "requests>=2.32.3",
    "skelly-synchronize",
    "skelly-viewer",
    "skellycam",
    "skellyforge",
    "skellytracker",
]

[tool.uv.sources]
skellycam = { git = "https://github.com/freemocap/skellycam", branch = "jon/development" }
skellytracker = { git = "https://github.com/freemocap/skellytracker", branch = "jon/development" }
skellyforge = { git = "https://github.com/freemocap/skellyforge" }
skelly-viewer = { git = "https://github.com/freemocap/skellyviewer" }
freemocap-blender-addon = { git = "https://github.com/freemocap/freemocap_blender_addon" }
skelly-synchronize = { git = "https://github.com/freemocap/skelly_synchronize" }

[project.scripts]
skellycam = "freemocap.__main__:main"

[tool.uv]
package = true