name: Linting Flake8

on:
  workflow_dispatch:
  pull_request:
    branches: [main, development]
    paths:
    - 'freemocap/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: clonedSemicolon/setup-strace@v13
    - name: Set up Python 3.x
      uses: wntrblm/nox@2022.8.7
      with:
        python-versions: "3.12"
    - name: Run noxfile
      run: |
        nox --session lint
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
