name: Upload Python Package

on:
  push:
    branches:
    - missingno

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing - https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: clonedSemicolon/setup-strace@v13
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install LLVM
      run: sudo apt-get update && sudo apt-get install -y llvm


    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Cache Poetry dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Update dependencies
      run: poetry update

    - name: Install dependencies
      run: poetry install

    - name: Build package
      run: poetry build

    - name: Publish package to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
