name: Freemocap Tests

on:
  pull_request:
    branches: [ main, development ]
    paths: 
      - 'freemocap/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: System Info
        run: |
          uname -a || true
          lsb_release -a || true
          gcc --version || true
          env
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Install libxcb
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
      - name: Install libegl1
        run: |
          sudo apt-get install -y libegl1-mesa
      - name: Run Tests with Pytest
        run: |
          pip install pytest
          pytest freemocap/tests
